
import React from 'react';
import { Difficulty } from '../types';
import { BrainIcon } from './icons/BrainIcon';

interface LevelSelectionProps {
  onSelectLevel: (difficulty: Difficulty) => void;
  quizLength: number;
}

const levels = [
  { difficulty: Difficulty.EASY, description: "Fundamental concepts and basic knowledge." },
  { difficulty: Difficulty.MEDIUM, description: "In-depth questions on regulations and processes." },
  { difficulty: Difficulty.HARD, description: "Challenging scenarios and advanced topics." },
];

export default function LevelSelection({ onSelectLevel, quizLength }: LevelSelectionProps) {
  return (
    <div className="text-center p-8 bg-white/10 backdrop-blur-sm rounded-2xl shadow-2xl border border-white/20 animate-fade-in">
      <div className="flex justify-center items-center mb-6">
         <BrainIcon className="h-16 w-16 text-cyan-300" />
      </div>
      <h1 className="text-4xl font-bold text-white mb-2">Food Safety AI Quiz</h1>
      <p className="text-lg text-slate-300 mb-8">Select your difficulty level to begin.</p>
      
      <div className="space-y-4">
        {levels.map(level => (
          <button
            key={level.difficulty}
            onClick={() => onSelectLevel(level.difficulty)}
            className="w-full bg-slate-700 text-white py-4 px-6 rounded-lg text-left hover:bg-slate-600 transition-all duration-300 transform hover:scale-105 shadow-lg focus:outline-none focus:ring-4 focus:ring-cyan-300/50"
          >
            <p className="text-xl font-bold text-cyan-400">{level.difficulty}</p>
            <p className="text-slate-300">{level.description}</p>
          </button>
        ))}
      </div>
       <p className="text-xs text-slate-400 mt-8">Each quiz consists of {quizLength} questions generated by AI.</p>
    </div>
  );
}
